 # tank_drive.on_for_rotations(20,20,1.5)
    # sleep(0.5)
    # D.turn90degright()
    # sleep(0.5)
    # tank_drive.on_for_rotations(20,20,0.2)
    # sleep(0.5)
    # tank_drive.on_for_rotations(-20,-20,0.2)
    # sleep(0.5)
    # D.turn90degright()
    # sleep(0.5)
    # D.findSurfaceColor(1); # drive until color black detected
    # sleep(0.5)
    # ### 
    # D.turn90degleft()
    # sleep(0.5)
    # tank_drive.on_for_rotations(20,20,0.2)
    # sleep(0.5)
    # D.turn90degleft()
    # sleep(0.5)
    # D.findSurfaceColor(4) # drive until color yellow detected
    # sleep(0.5)
    # D.turn180degright()
    # sleep(0.5)
    # D.findSurfaceColor(1) # drive until color black detected
    # sleep(0.5)
    # ###
    # D.turn90degleft()
    # sleep(0.5)
    # tank_drive.on_for_rotations(20,20,0.2)
    # sleep(0.5)
    # D.turn90degleft()
    # sleep(0.5)
    # tank_drive.on_for_rotations(20,20,2)
    # sleep(0.5)
    # D.turn90degleft()
    # sleep(0.5)
    # tank_drive.on_for_rotations(20,20,0.2)
    # sleep(0.5)
    # tank_drive.on_for_rotations(-20,-20,0.2)
    # sleep(0.5)
    # D.turn90degright()#
    # sleep(0.5)
    ######################